before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

language: node_js

before_install:
 - sudo apt-get install libgmp3-dev
 - "mysql -e 'create database browserid;'"

node_js:
 - 0.6

notifications:
  irc: "irc.mozilla.org#identity"

env:
 - WHAT_TESTS=front MYSQL_USER=root
 - WHAT_TESTS=back NODE_ENV=test_mysql MYSQL_USER=root
 - WHAT_TESTS=back NODE_ENV=test_json

mysql:
  adapter: mysql2
  username: root
  encoding: utf8
  database: browserid
