before_script:
  - sh -e /etc/init.d/xvfb start

language: python
python:
  - 2.6
  - 2.7

script: py.test --baseurl=http://dev.123done.org --driver=firefox -m travis tests

env:
  - DISPLAY=':99.0'

notifications:
  email:
    - dave.hunt@gmail.com
  irc:
    - "irc.mozilla.org#automation"
    - "irc.mozilla.org#identity"
